### ISSUE TITLE
[Bug] Several? intro incomplete

### ISSUE THREAD

**Issue by OdinVex** [danieladov/jellyfin-plugin-themesongs#28]
Several theme songs are cut a bit at the beginning. Maybe intentional, maybe not? Edit: Found slider for player, they're cut starting. Not sure why.

**Comment by stpnwf** [comment]
Yes, they are so short and start/end so abruptly... And they don't repeat by default, which is odd, if they are going to be so short...
Other than they repeating by default, I would like to suggest the option so that users can change the default source of where the intros are downloaded, so that if other users want to, out of their own will, create their own repos with alternative intro songs, or slightly longer ones, we can have that option...
